# Generated by Django 4.1.6 on 2023-05-04 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Product Initially created'), ('sales', 'Product Sold'), ('dispose', 'Product Expired'), ('date changed', 'Product expiry date changed'), ('rework_decr', 'Rework from store to the kitchen'), ('rework_incr', 'Rework done... from kitchen back to store'), ('refill', 'Product Refillment'), ('change', 'Product Updated in Expense tracking')], default=None, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hoteldata')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.variantdetails')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('hotel', 'user', 'product_id', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('request', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(choices=[('expiry', 'Expiry'), ('request', 'Request')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hoteldata')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenItemRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='request', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='sent', max_length=50)),
                ('request', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('hotel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hoteldata')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryProductAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_by', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(max_length=10)),
                ('description', models.CharField(default=None, max_length=100)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hoteldata')),
                ('inventory_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryproduct')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
