# Generated by Django 4.1.6 on 2023-11-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
        ("sales", "0003_bill_sales_bill_hotel_i_4bec9a_idx_and_more"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryproduct",
            unique_together={("hotel", "product_id", "variant")},
        ),
    ]
