# Generated by Django 4.1.6 on 2023-10-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["hotel_id", "created_at"], name="sales_bill_hotel_i_2fa4b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customers",
            index=models.Index(
                fields=["hotel_id", "created_at"], name="sales_custo_hotel_i_8bd6f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemordered",
            index=models.Index(
                fields=["hotel_id", "created_at"], name="sales_itemo_hotel_i_fa7f3e_idx"
            ),
        ),
    ]
