# Generated by Django 4.1.6 on 2023-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_bill_sales_bill_hotel_i_2fa4b4_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["hotel_id", "bill_status", "created_at"],
                name="sales_bill_hotel_i_4bec9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemordered",
            index=models.Index(
                fields=["hotel_id", "status", "created_at"],
                name="sales_itemo_hotel_i_f334b9_idx",
            ),
        ),
    ]
